artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://chicken-disease-dataset.s3.us-east-2.amazonaws.com/chicken-fecal-images.zip?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEFUaCXVzLWVhc3QtMiJGMEQCIHW63LeFMhptYzDoiioABI3bEoMiu59WJRzap333RoqYAiA74hP4scXF0uI3Dk6%2BHdxmfMHVkJara1vKZkgJUvNQxSrxAgi%2B%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAAaDDY4ODU2NzI3MDg1OCIMtFxOK7csZvVmKuXiKsUCNfVrzPasswoSyfEpbUUbqJpnAfw1BKRj7Lwik9hdlFUCuQ0puLmPXm086k%2B8kXW%2BLSjIRdS3jSLTGnId2EYd4%2FvcH5nxI6dcR4uPABZn%2Bj6%2FaxEBTMwl80GqwymmppNlsdsmX6y%2B5lS5gDfiEsBFBu2%2F1GRhJv5VBCXAdocY8%2Bg1IFPQ8%2Fj2cFdNurtQAypHltRLt3gOxBissS3PC7pbuAbY1NG9k6y3yqb5OHyJwBVdUmtXDJfUcAKnpi%2Bk%2FehJP5oWCL1LMfCmEbX1bAt9C2V%2BHNbb6rX12MY0cu7de3r0dbjQdf47y8r4GIsUHGPDz6txR0YYMSMIJoLVaZelRDoQ7UrOdVAp4utMLDB4Lc6KvzwkQWKeMuFCDZPS3m2vr5tdSIWLARd6zWwtYnN9o7QiJAHbTMwt2K46Va8756j9gJ3C4zCJ3OO4Bjq0AnvClTuj%2FpvEMDmr8OXQdF6VbbBCCnPnePhuHV%2FFtcZclYI%2FgKCecRwXcW3%2FS5J4qj2pHfkw%2FeCEmE9A6tkWHbBf81t8o5bVbiKYB5g1rESI0wZpbFWyxUFRflgXyT5pqAmRdGp4sN4zP0xIY8xmJ238xZXcgYAUBuyzKqQ8SI8jHspqYduTI88173TaOHO3rJ%2BIeADXdHUKpMTdv26fT%2B2CBdJYtyoS6J0X6mLiE5MsF642QjN4%2BWvIt7gJ01NZBRfih8y0ZiEzdFmMUqRz0dyDig1JtZkmSDig%2BfPq4w17r%2B7BbJPpE2QSHBiQP1M3B0lDym0zVsehbRm%2FEVXSxzKpYRruGg%2FZ20tyZtEhUw6iS%2FSzGeUaDXJfYIZKv8hO1wP1j8Uh93vMgmm6EdvkUTK2Gmsb&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241023T123741Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIA2AUOOXXFGXV3WXWM%2F20241023%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Signature=568b2c635e5c83361531805d0c6dc89ea9e5e8483e1ee782a17d981ffea39260
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_sorting:
  root_dir: artifacts/data_sorting
  source_csv: artifacts/data_ingestion/train_data.csv
  output_dir: artifacts/data_sorting/sorted_images


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5