artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://chicken-disease-dataset.s3.us-east-2.amazonaws.com/chicken-fecal-images.zip?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEC8aCXVzLWVhc3QtMiJHMEUCIEW4mphlrxwF9f9Ww%2BXbYIBuUmhlPG0n81w7RbHxN41SAiEAnSpKnb4Hl2EhwD3dUmSGtoyZcofqGIrmA0XTlWOV%2F1cq8QIImP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgw2ODg1NjcyNzA4NTgiDPg5TZiK%2FEQVP%2Br9rCrFArZK2HqwAgRpoSTuJOa%2Fz2pthW%2Bkmg%2Bnpy%2FnjqFqWWvmw7yn3Hbx6RlE0kkVkPHCqT%2FSSIUUzDckxqxaB9KCedM%2B67K3tXCyPsZI9GfnDwS73ut5ax9BawD625UnOxbxgyF12SfJu0G922f6vp%2Fpz8TZvdYZIGD1%2FZhIKuDrcvSFBzX%2F4aMcBXMeEdRWOykhFvl1oD2vkoPWmzccXWqvPx5LM9WZ4Z9cgwvm8b%2BCCNLFdU9iZuXZ61utYPGc8MKy1zo4ydH%2BueuvD%2BCkpY2AjowqPOPdAMZyUPWzSfE3nERd6NCoqcbftK5Jo6bcYu3rseTu4DE089KlMgTz3Q7FSUudtSSxVM42esR00lb9AvN6VVGTKrzOQTDqogUffKJvKooYAWBwdCnfC0Us3g4UIHkHeBTbp7paP%2FC7JwKTiOkoaanY2m8w%2Fa%2FbuAY6swJ4B5uDRToou6A845Dc5wuNVVzb1Xoojg1ai%2FCJd8IIMTOBeqLmlDsqbhBBN8TNFJbojQC6Z2NxgLd96w93vZPkCDwmpe36LoENQDiLtnFJxNdCd%2FWL7XQ%2FGAb6Vyz9a4HYWbu760a4177b3NXfVe%2B%2Fws2hVTAXpP7lhPjzMmYG0Hmc3L%2FYxoquWoQZXXDJ6iPe8%2Fn5El%2FuVdZAjdpCRTxvlB%2BQdPhLlCEDiUEhWRBaEf2TOLyh6J1bKMNN4S%2BK48f2MMeAZKUb3cNcn6jAB1bOTNLkWbatEOKDuArqRy%2Fuh6tJ7e8GhD52Exfv69cSINeL7ys%2BYJ5SjY0OC7zAqXLkoQsXyYV7gYD6WN8ReWwwF%2BIxGHhdTHMaRpC35RHm6sjnuh1DMPdAW4FLflwB73FlJSXW&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241021T224204Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIA2AUOOXXFLMKXZR6S%2F20241021%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Signature=dd1bcda8f8b722beef3716babc5a9d652a0c6e1bb8f128f4e2915454fb1ad4b1
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_sorting:
  root_dir: artifacts/data_sorting
  source_csv: artifacts/data_ingestion/train_data.csv
  output_dir: artifacts/data_sorting/sorted_images


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5