artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://chicken-disease-dataset.s3.us-east-2.amazonaws.com/chicken-fecal-images.zip?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMiJGMEQCIFK%2FxU6wGrhv4b74RnAfXDuH4MSH7ZTjwWWwOwHBgrhIAiBcJ6bLgvyQhlsxo0HO6ler%2FhikedeevINLCPTEyXfisyrxAgio%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAAaDDY4ODU2NzI3MDg1OCIMp7iAbBQ58RtPkrpfKsUCoNQESBVRFfzedzf0b5p0F7d%2B3Fj1elrWXIWgMhN18DdLCzbdVUS0QTRwlaxcaDvYBabE0PnRsN%2FtvnfNr8VbbagM9wzHwNfUr5x7eRwj1tjg%2BliZHg%2FfGXtnmqCcwA0dEQVxz1l7buPQShJIbnIY%2F0IRXcCFi0wYizY%2Fq3tFt9IxB8NjsvDe5MBYjDK%2BgmjfaYqYvC1twZgh3yGHhWbwTTeUkUgTy27QhX%2FxAuX6Kn8CsmUcmWwd76TllAHGYjKwvgg4bdALODaG%2FE09jykMHwmNj7xhICd6r5kEFx1gesaQ5iobh8YpQgyIoOuS250oAJplHCPeSlpP8wCbnblNUPdeYFWgV0Pl7SsmjLTK3bPnd4yn89y8hQbl%2F83xAKDuXp2lrYZARM%2BZogyO36%2BOBJTrBZLBn40JFI48Ncs1dxvI2QZ%2FNTDa9t64Bjq0AhVhw%2Fa2rUWOPjcIksyw9Peon61Z1fless8g0E3pFCp0Z6Gj%2BIMRl96bLzBfHu1E1gZaJNxLalsAA7wrE07%2BVzF%2Fdife3oRdJPeCQdUc5bqovhhkZ7bqSyfZHkbz0pyMy%2BP%2Btawa3IJMMEmJtS%2BWrPzmPaF%2FA8aewqdvOuaIPI%2B2Wa682aJY7SBQtCik7OGMg6BLespM0tbKPj5V9iVLjMUqwksco5jm4hq25nw9%2BTG4qfIvBiAlBzSTq40elGTaYmebPdw6tpRi%2FQCUz5Vt8%2FlgEBaJzcdCMzNyR5nQNKE8muUlg3YgtTDmX8bcLoAjhVMiZCJny%2BRjk1OT0Mtsfs48MDotj5QcW2Fe4g0BYdRmkmyCOozvmDtYfdBNp0Poz4jip08i5ECOlGxuP4HZeN2lqoXU&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241022T144909Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIA2AUOOXXFKVW6JEJI%2F20241022%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Signature=741587cfd354ef94643dee119e7f1c7beefda7ab2e4bea3d9e15f350e1cdf406
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_sorting:
  root_dir: artifacts/data_sorting
  source_csv: artifacts/data_ingestion/train_data.csv
  output_dir: artifacts/data_sorting/sorted_images


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5